CREATE DATABASE QLGV
GO

USE QLGV
GO

CREATE TABLE GIAOVIEN
(
	MAGV char(10),
	HOTEN nvarchar(50),
	LUONG float,
	PHAI nvarchar(10),
	NGAYSINH date,
	DIACHI nvarchar(150),
	GVQLCM	char(10),
	MABM char(10),

	CONSTRAINT PK_GIAOVIEN PRIMARY KEY (MAGV)
)

CREATE TABLE GV_DT
(
	MAGV char(10),
	DIENTHOAI varchar(15),

	CONSTRAINT PK_GV_DT PRIMARY KEY (MAGV, DIENTHOAI)
)

CREATE TABLE BOMON
(
	MABM char(10),
	TENBM nvarchar(50),
	PHONG nvarchar(20),
	DIENTHOAI varchar(15),
	TRUONGBM char(10),
	MAKHOA char(10),
	NGAYNHANCHUC date,

	CONSTRAINT PK_BOMON PRIMARY KEY (MABM)
)

CREATE TABLE KHOA
(
    MAKHOA char(10),
    TENKHOA nvarchar(50),
    NAMTL date,
    PHONG nvarchar(20),
    DIENTHOAI varchar(15),
    TRUONGKHOA char(10),
    NGAYNHANCHUC date

	CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
)

CREATE TABLE DETAI
(
	MADT char(10),
	TENDT nvarchar(50),
	KINHPHI money,
	CAPQL nvarchar(20),
	NGAYBD date,
	NGAYKT date,
	MACD char(10),
	GVCNDT char(10),

	CONSTRAINT PK_DETAI PRIMARY KEY (MADT)
)

CREATE TABLE CHUDE
(
	MACD char(10),
	TENCD nvarchar(50),

	CONSTRAINT PK_CHUDE PRIMARY KEY (MACD)
)

CREATE TABLE CONGVIEC
(
	MADT char(10),
	STT int,
	TENCV nvarchar(50),
	NGAYBD date,
	NGAYKT date,

	CONSTRAINT PK_CONGVIEC PRIMARY KEY (MADT, STT)
)

CREATE TABLE THAMGIADT
(
	MAGV char(10),
	MADT char(10),
	STT int,
	PHUCAP float,
	KETQUA nvarchar(15),

	CONSTRAINT PK_THAMGIADT PRIMARY KEY (MAGV, MADT, STT)
)

CREATE TABLE NGUOI_THAN
(
	MAGV char(10),
	TEN nvarchar(50),
	NGSINH date,
	PHAI nvarchar(10),

	CONSTRAINT PK_NGUOI_THAN PRIMARY KEY (MAGV, TEN)
)

--GIAOVIEN
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_GIAOVIEN
FOREIGN KEY (GVQLCM)
REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_BOMON
FOREIGN KEY (MABM)
REFERENCES BOMON(MABM)

--GV_DT
ALTER TABLE GV_DT
ADD CONSTRAINT FK_GV_DT
FOREIGN KEY (MAGV)
REFERENCES GIAOVIEN(MAGV)

--BOMON
ALTER TABLE BOMON
ADD CONSTRAINT FK_BOMON_KHOA
FOREIGN KEY (MAKHOA)
REFERENCES KHOA(MAKHOA)

ALTER TABLE BOMON
ADD CONSTRAINT FK_BOMON_GIAOVIEN
FOREIGN KEY (TRUONGBM)
REFERENCES GIAOVIEN(MAGV)

--KHOA
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA
FOREIGN KEY (TRUONGKHOA)
REFERENCES GIAOVIEN(MAGV)

--DETAI
ALTER TABLE DETAI
ADD CONSTRAINT DETAI_GIAOVIEN
FOREIGN KEY (GVCNDT)
REFERENCES GIAOVIEN(MAGV)

ALTER TABLE DETAI
ADD CONSTRAINT FK_DETAI_CHUDE
FOREIGN KEY (MACD)
REFERENCES CHUDE(MACD)

--CONGVIEC
ALTER TABLE CONGVIEC
ADD CONSTRAINT FK_CONGVIEC
FOREIGN KEY (MADT)
REFERENCES DETAI(MADT)

--THAMGIADT
ALTER TABLE THAMGIADT
ADD CONSTRAINT FK_THAMGIADT_CONGVIEC
FOREIGN KEY (MADT, STT)
REFERENCES CONGVIEC(MADT, STT)

ALTER TABLE THAMGIADT
ADD CONSTRAINT FK_THAMGIADT_GIAOVIEN
FOREIGN KEY (MAGV)
REFERENCES GIAOVIEN(MAGV)

--NGUOI_THAN
ALTER TABLE NGUOI_THAN
ADD CONSTRAINT FK_NGUOI_THAN
FOREIGN KEY (MAGV)
REFERENCES GIAOVIEN(MAGV)






